{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d37ac484",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "# ---------------------------\n",
    "# Title\n",
    "# ---------------------------\n",
    "st.title(\"Sales Dashboard\")\n",
    "\n",
    "# ---------------------------\n",
    "# File uploader\n",
    "# ---------------------------\n",
    "uploaded_file = st.file_uploader(\n",
    "    \"Upload your sales data (XLSX)\",\n",
    "    type=\"xlsx\"\n",
    ")\n",
    "\n",
    "if uploaded_file is not None:\n",
    "\n",
    "    # Read Excel file\n",
    "    df = pd.read_excel(uploaded_file)\n",
    "\n",
    "    # Create vendor column\n",
    "    df['VENDOR'] = df['NAME'] + ' ' + df['LASTNAME']\n",
    "\n",
    "    # ---------------------------\n",
    "    # FILTER SECTION\n",
    "    # ---------------------------\n",
    "    st.header(\"Filters\")\n",
    "\n",
    "    # Region filter\n",
    "    regions = [\"Todas\"] + list(df['REGION'].unique())\n",
    "\n",
    "    selected_region = st.selectbox(\n",
    "        \"Select a region\",\n",
    "        regions\n",
    "    )\n",
    "\n",
    "    # Apply filter\n",
    "    if selected_region == \"Todas\":\n",
    "        filtered_data = df\n",
    "    else:\n",
    "        filtered_data = df[df['REGION'] == selected_region]\n",
    "\n",
    "    # Show filtered table\n",
    "    st.subheader(\"Filtered Data\")\n",
    "    st.write(filtered_data)\n",
    "\n",
    "    # ---------------------------\n",
    "    # VENDOR DETAILS SECTION\n",
    "    # ---------------------------\n",
    "    st.header(\"Vendor Details\")\n",
    "\n",
    "    selected_vendor = st.selectbox(\n",
    "        \"Select a vendor\",\n",
    "        sorted(df['VENDOR'].unique())\n",
    "    )\n",
    "\n",
    "    vendor_df = df[df['VENDOR'] == selected_vendor]\n",
    "\n",
    "    st.write(vendor_df)\n",
    "\n",
    "    # ---------------------------\n",
    "    # GRAPHS SECTION\n",
    "    # ---------------------------\n",
    "    st.header(\"Sales Histograms\")\n",
    "\n",
    "    # These charts are independent from vendor selection\n",
    "\n",
    "    col1, col2, col3 = st.columns(3)\n",
    "\n",
    "    # ---------------------------\n",
    "    # Histogram 1: SOLD UNITS\n",
    "    # ---------------------------\n",
    "    with col1:\n",
    "\n",
    "        fig1, ax1 = plt.subplots()\n",
    "\n",
    "        ax1.hist(\n",
    "            filtered_data['SOLD UNITS'],\n",
    "            bins=10\n",
    "        )\n",
    "\n",
    "        ax1.set_title(\"Units Sold\")\n",
    "        ax1.set_xlabel(\"Units\")\n",
    "        ax1.set_ylabel(\"Frequency\")\n",
    "\n",
    "        st.pyplot(fig1)\n",
    "\n",
    "    # ---------------------------\n",
    "    # Histogram 2: TOTAL SALES\n",
    "    # ---------------------------\n",
    "    with col2:\n",
    "\n",
    "        fig2, ax2 = plt.subplots()\n",
    "\n",
    "        ax2.hist(\n",
    "            filtered_data['TOTAL SALES'],\n",
    "            bins=10\n",
    "        )\n",
    "\n",
    "        ax2.set_title(\"Total Sales\")\n",
    "        ax2.set_xlabel(\"Sales\")\n",
    "        ax2.set_ylabel(\"Frequency\")\n",
    "\n",
    "        st.pyplot(fig2)\n",
    "\n",
    "    # ---------------------------\n",
    "    # Histogram 3: SALES AVERAGE\n",
    "    # ---------------------------\n",
    "    with col3:\n",
    "\n",
    "        fig3, ax3 = plt.subplots()\n",
    "\n",
    "        ax3.hist(\n",
    "            filtered_data['SALES AVERAGE'],\n",
    "            bins=10\n",
    "        )\n",
    "\n",
    "        ax3.set_title(\"Average Sales\")\n",
    "        ax3.set_xlabel(\"Average\")\n",
    "        ax3.set_ylabel(\"Frequency\")\n",
    "\n",
    "        st.pyplot(fig3)\n",
    "\n",
    "else:\n",
    "\n",
    "    with st.spinner(\"Waiting for file upload...\"):\n",
    "        st.empty()"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
